name: Update Disposable Email Blocklist

on:
  schedule:
    # Run every Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest blocklist
        run: curl -sL "https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/refs/heads/main/disposable_email_blocklist.conf" -o disposable_email_blocklist.conf

      - name: Compare and Update
        id: compare
        run: |
          if ! diff -q disposable_email_blocklist.conf priv/disposable_email_blocklist.conf; then
            echo "Blocklist has changed. Updating..."
            cp disposable_email_blocklist.conf priv/disposable_email_blocklist.conf
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add priv/disposable_email_blocklist.conf
            git commit -m "chore(deps): Update disposable email blocklist"
            echo "branch_name=update-blocklist-file" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in blocklist."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            echo "branch_name=" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.compare.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): Update disposable email blocklist'
          title: 'chore(deps): Update disposable email blocklist'
          body: |
            This PR updates the `disposable_email_blocklist.conf` file to the latest version from the upstream repository.
            It is automatically generated by a scheduled GitHub Actions workflow.
          branch: update-blocklist-file
          base: main
          delete-branch-if-merged: false
